FROM docker.io/library/ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
ENV http_proxy= https_proxy= HTTP_PROXY= HTTPS_PROXY=
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    bash ca-certificates coreutils findutils grep sed gawk \
        python3 python3-dev python3-numpy python3-decorator python3-sympy python3-scipy python3-attr python3-psutil \
        g++ make cmake \
        libgomp1 libstdc++6 \
 && rm -rf /var/lib/apt/lists/*
